### PR TITLE
Edited func_monitor and point_camera

### PR DESCRIPTION
**Pull request by ghost**
func_monitor is now a mesh based entity, as it should be. Also, removed the frustrum from point_camera to make it easier to align.

### CODE REVIEW

**Comment by gvarados1** [comment]
frustrum is nice

**Comment by gvarados1** [comment]
how does removing it make it easier to align? I don't have any problems with it.

**Comment by chrjen** [comment]
Thank you for your changes. Unfortunately I can't accept them though. The frustum is there for a reason as it helps visualise what is seen by the camera, so I won't apply your solution to everyone. So please either keep your changes locally or come up with a different solution.

**Comment by chrjen** [comment]
Added your SolidClass fix in bea580affef16d787d44a2af606ed09c11cae6d0

**Pull request closed without merging**
